from fpdf import FPDF, HTMLMixin
from Rendimiento import Rendimiento
#sudo pip install pillow
#sudo pip install fpdf2
def createPdf(rendimiento):
    html = '<h1 align="center">Administracion de Rendimiento</h1>'
    html += '<h3>No. de Equipo: 1</h3>'
    html += '<h3>Integrantes:</h3>'
    html += '<ul>'
    html += '<li>Gomez Gonzalez Kevin</li>'
    html += '<li>Melendez Padilla Mauricio</li>'
    html += '<li>Osorio Esli</li>'
    html += '<li>Fernando</li>'
    html += '</ul>'
    html += '<br/>'
    html += '<h3>Fecha de Elaboracion: 06/05/2019 </h3>'
    html += '<table border="0" >'
    html += '<thead>'
    html += '<tr>'
    html += '<th width="40%">Sistema Operativo del Servidor</th>'
    html += '<th width="30%">Tiempo de actividad del Servidor</th>'
    html += '<th width="30%">Numero de interfaces</th>'
    html += '</tr>'
    html += '</thead>'
    html += '<tbody>'
    html += '<tr>'
    html += '<td align="center" width="40%">Fedora</td>'
    html += '<td align="center" width="30%">10</td>'
    html += '<td align="center" width="30%">5</td>'
    html += '</tr>'
    html += '</tbody>'
    html += '</table>'
    html += '<br/>'
    html += '<h3>Informacion grafica del CPU:</h3>'
    html += '<img src="mila.jpg" width="256" height="171">'
    html += '<br/>'
    html += '<h3>Informacion grafica de uso de memoria RAM:</h3>'
    html += '<img src="mila.jpg" width="256" height="171">'
    html += '<br/>'
    html += '<h3>Informacion grafica de uso de Disco Duro:</h3>'
    html += '<img src="mila.jpg" width="256" height="171">'
    html += '<br/>'
    html += '<h3>Supervision de Servidores</h3>'
    html += '<table border="0" >'
    html += '<thead>'
    html += '<tr>'
    html += '<th width="50%">Sensor SMTP y POP3</th>'
    html += '<th width="50%"></th>'
    html += '</tr>'
    html += '</thead>'
    html += '<tbody>'
    html += '<tr>'
    html += '<td align="left" width="50%">Tiempo de respuesta del servidor SMTP</td>'
    html += '<td align="left" width="50%">10 s</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td align="left" width="50%">Tiempo de respuesta del servidor POP3</td>'
    html += '<td align="left" width="50%">10 s</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td align="left" width="50%">Suma de ambos tiempos de respuesta</td>'
    html += '<td align="left" width="50%">10 s</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td align="left" width="50%">Status del servidor</td>'
    html += '<td align="left" width="50%">Start</td>'
    html += '</tr>'
    html += '</tbody>'
    html += '</table>'
    html += '<table border="0" >'
    html += '<thead>'
    html += '<tr>'
    html += '<th width="50%">Sensor HTTP</th>'
    html += '<th width="50%"></th>'
    html += '</tr>'
    html += '</thead>'
    html += '<tbody>'
    html += '<tr>'
    html += '<td align="left" width="50%">Tiempo de respuesta de una solicitud HTTP</td>'
    html += '<td align="left" width="50%">10 s</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td align="left" width="50%">Bytes recibidos</td>'
    html += '<td align="left" width="50%">10 s</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td align="left" width="50%">Ancho de banda</td>'
    html += '<td align="left" width="50%">10 s</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td align="left" width="50%">Status del servidor</td>'
    html += '<td align="left" width="50%">Start</td>'
    html += '</tr>'
    html += '</tbody>'
    html += '</table>'
    html += '<table border="0" >'
    html += '<thead>'
    html += '<tr>'
    html += '<th width="50%">Sensor FTP</th>'
    html += '<th width="50%"></th>'
    html += '</tr>'
    html += '</thead>'
    html += '<tbody>'
    html += '<tr>'
    html += '<td align="left" width="50%">Tiempo de respuesta del servidor</td>'
    html += '<td align="left" width="50%">10 s</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td align="left" width="50%">Respuesta del servidor</td>'
    html += '<td align="left" width="50%">10 s</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td align="left" width="50%">Status del servidor</td>'
    html += '<td align="left" width="50%">Start</td>'
    html += '</tr>'
    html += '</tbody>'
    html += '</table>'
    html += '<table border="0" >'
    html += '<thead>'
    html += '<tr>'
    html += '<th width="50%">Sensor FTP Server File Count</th>'
    html += '<th width="50%"></th>'
    html += '</tr>'
    html += '</thead>'
    html += '<tbody>'
    html += '<tr>'
    html += '<td align="left" width="50%">Recuento de archivos</td>'
    html += '<td align="left" width="50%">10</td>'
    html += '</tr>'
    html += '</tbody>'
    html += '</table>'
    html += '<table border="0" >'
    html += '<thead>'
    html += '<tr>'
    html += '<th width="50%">Sensor DNS</th>'
    html += '<th width="50%"></th>'
    html += '</tr>'
    html += '</thead>'
    html += '<tbody>'
    html += '<tr>'
    html += '<td align="left" width="50%">Tiempo de respuesta del servidor</td>'
    html += '<td align="left" width="50%">10 s</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td align="left" width="50%">Status del servidor</td>'
    html += '<td align="left" width="50%">Start</td>'
    html += '</tr>'
    html += '</tbody>'
    html += '</table>'
    html += '<table border="0" >'
    html += '<thead>'
    html += '<tr>'
    html += '<th width="50%">Sensor Acceso Remoto</th>'
    html += '<th width="50%"></th>'
    html += '</tr>'
    html += '</thead>'
    html += '<tbody>'
    html += '<tr>'
    html += '<td align="left" width="50%">Numero de conexiones</td>'
    html += '<td align="left" width="50%">10</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td align="left" width="50%">Trafico enviado y recibido</td>'
    html += '<td align="left" width="50%">10</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td align="left" width="50%">Tiempo de actividad de las conexiones</td>'
    html += '<td align="left" width="50%">10</td>'
    html += '</tr>'
    html += '<tr>'
    html += '<td align="left" width="50%">Status del servidor</td>'
    html += '<td align="left" width="50%">Start</td>'
    html += '</tr>'
    html += '</tbody>'
    html += '</table>'
    class MyFPDF(FPDF, HTMLMixin):
        pass
    pdf = MyFPDF()
    pdf.add_page()
    pdf.write_html(html)
    pdf.output('ReporteAdministracionRendimiento.pdf', 'F')
rendimiento = Rendimiento()
createPdf(rendimiento)